name: Lint Bash Scripts
on: [push]
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck
    - name: Run shellcheck
      run: shellcheck *.sh
